# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b301abb19ac02155ec40f5479ace87f1918e6584a6a8abf65854585c70b49886e3ce80374725adbbb8df2f26a5e95ac50d832bafe0c05ec0612fbc5eed564bfa

test:
  secret_key_base: ea1416cc94351ba1b032e9d52dfdc80b680302de222af455fb8d52f53b0e17e213eb256d8a5bbee8987c0b6c49cf2545892700659cb01e9b66a99b03dd8ec86c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
